import os
import urllib3
import requests
import json
import xml.dom.minidom

# Suppress InsecureRequestWarning (Not recommended for production)
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

def build_payload():
    """
    Constructs the JSON payload for the POST request.

    Returns:
        str: The JSON-formatted payload as a string.
    """
    payload = {
        "subClientProperties": {
            "commonProperties": {
                "impersonateUserCredentialinfo": {"credentialId": 0}
            },
            "useLocalContent": True,
            "subClientEntity": {
                "subclientId": 1776,
                "subclientName": "default",
                "instanceId": 143,
                "clientId": 491,
                "applicationId": 134
            },
            "fsSubClientProp": {
                "includePolicyFilters": False,
                "useGlobalFilters": "OFF",
                "customSubclientContentFlags": 0,
                "customSubclientFlag": True,
                "openvmsBackupDate": False
            },
            "cloudAppsSubClientProp": {
                "instanceType": "AZURE_BLOB",
                "objectStorageSubclient": {"backupContentType": "CONTENT_BASED"}
            },
            "content": [
                # Include all containers for backup
                {"path": "/app-dae"},
                {"path": "/app-gdm"},
                {"path": "/app-hld"},
                {"path": "/app-ldg"},
                {"path": "/app-pdb"},
                {"path": "/app-ser"},
                {"path": "/demo"},
                {"path": "/lab"},
                {"path": "/laboratory"},
                {"path": "/raw"},
                {"path": "/samples-dae"},
                {"path": "/src-blackrock"},
                {"path": "/src-broadridge"},
                {"path": "/src-cvent"},
                {"path": "/src-mandatewire"},
                {"path": "/src-mmd"},
                {"path": "/src-on24"},
                {"path": "/src-pivotal-crm"},
                {"path": "/src-vdm"},
                {"path": "/synapse"},
                {"path": "/synfs-gmoperfsyslwr"},
                # Transient folders
                {"excludePath": "/app-gdm/transient"},
                {"excludePath": "/src-vdm/transient"},
                # src-vdm vendor data exclusions
                {"excludePath": "/src-vdm/cleansed/factset/gr-v2/gr-item"},
                {"excludePath": "/src-vdm/cleansed/factset/gr-v2/gr-report"},
                {"excludePath": "/src-vdm/cleansed/factset/own-v5/own-ent-13f-filing-hist"},
                {"excludePath": "/src-vdm/cleansed/factset/own-v5/own-ent-fund-filing-hist"},
                {"excludePath": "/src-vdm/cleansed/factset/own-v5/own-ent-funds"},
                {"excludePath": "/src-vdm/cleansed/factset/own-v5/own-ent-institutions"},
                {"excludePath": "/src-vdm/cleansed/factset/own-v5/own-fund-detail"},
                {"excludePath": "/src-vdm/cleansed/factset/own-v5/own-fund-generic"},
                {"excludePath": "/src-vdm/cleansed/factset/own-v5/own-inst-13f-detail"},
                {"excludePath": "/src-vdm/cleansed/factset/own-v5/own-inst-stakes-detail"},
                {"excludePath": "/src-vdm/cleansed/factset/own-v5/own-sec-coverage"},
                {"excludePath": "/src-vdm/cleansed/factset/own-v5/own-sec-prices"},
                {"excludePath": "/src-vdm/cleansed/factset/ref-v2/entity-type-map"},
                {"excludePath": "/src-vdm/cleansed/factset/sym-v1/sym-coverage"},
                {"excludePath": "/src-vdm/cleansed/factset/sym-v1/sym-entity"},
                {"excludePath": "/src-vdm/cleansed/factset/tv-v2/tv-esg-ranks"},
                {"excludePath": "/src-vdm/cleansed/factset/tv-v2/tv-insight"},
                {"excludePath": "/src-vdm/cleansed/factset/tv-v2/tv-momentum"},
                {"excludePath": "/src-vdm/cleansed/factset/tv-v2/tv-pulse"},
                {"excludePath": "/src-vdm/cleansed/factset/tv-v2/tv-volume"},
                {"excludePath": "/src-vdm/cleansed/ivydb-asia/dbo/currency"},
                {"excludePath": "/src-vdm/cleansed/ivydb-asia/dbo/option-price"},
                {"excludePath": "/src-vdm/cleansed/ivydb-asia/dbo/option-price-2004"},
                {"excludePath": "/src-vdm/cleansed/ivydb-asia/dbo/option-price-2005"},
                {"excludePath": "/src-vdm/cleansed/ivydb-asia/dbo/option-price-2006"},
                {"excludePath": "/src-vdm/cleansed/ivydb-asia/dbo/option-price-2007"},
                {"excludePath": "/src-vdm/cleansed/ivydb-asia/dbo/option-price-2008"},
                {"excludePath": "/src-vdm/cleansed/ivydb-asia/dbo/option-price-2009"},
                {"excludePath": "/src-vdm/cleansed/ivydb-asia/dbo/option-price-2010"},
                {"excludePath": "/src-vdm/cleansed/ivydb-asia/dbo/option-price-2011"},
                {"excludePath": "/src-vdm/cleansed/ivydb-asia/dbo/option-price-2012"},
                {"excludePath": "/src-vdm/cleansed/ivydb-asia/dbo/option-price-2013"},
                {"excludePath": "/src-vdm/cleansed/ivydb-asia/dbo/option-price-2014"},
                {"excludePath": "/src-vdm/cleansed/ivydb-asia/dbo/option-price-2015"},
                {"excludePath": "/src-vdm/cleansed/ivydb-asia/dbo/option-price-2016"},
                {"excludePath": "/src-vdm/cleansed/ivydb-asia/dbo/option-price-2017"},
                {"excludePath": "/src-vdm/cleansed/ivydb-asia/dbo/option-price-2018"},
                {"excludePath": "/src-vdm/cleansed/ivydb-asia/dbo/option-price-2019"},
                {"excludePath": "/src-vdm/cleansed/ivydb-asia/dbo/security-price"},
                {"excludePath": "/src-vdm/cleansed/ivydb-canada/dbo/option-info"},
                {"excludePath": "/src-vdm/cleansed/ivydb-canada/dbo/option-price"},
                {"excludePath": "/src-vdm/cleansed/ivydb-canada/dbo/option-price-2006"},
                {"excludePath": "/src-vdm/cleansed/ivydb-canada/dbo/option-price-2007"},
                {"excludePath": "/src-vdm/cleansed/ivydb-canada/dbo/option-price-2008"},
                {"excludePath": "/src-vdm/cleansed/ivydb-canada/dbo/option-price-2009"},
                {"excludePath": "/src-vdm/cleansed/ivydb-canada/dbo/option-price-2010"},
                {"excludePath": "/src-vdm/cleansed/ivydb-canada/dbo/option-price-2011"},
                {"excludePath": "/src-vdm/cleansed/ivydb-canada/dbo/option-price-2012"},
                {"excludePath": "/src-vdm/cleansed/ivydb-canada/dbo/option-price-2013"},
                {"excludePath": "/src-vdm/cleansed/ivydb-canada/dbo/option-price-2014"},
                {"excludePath": "/src-vdm/cleansed/ivydb-canada/dbo/option-price-2015"},
                {"excludePath": "/src-vdm/cleansed/ivydb-canada/dbo/option-price-2016"},
                {"excludePath": "/src-vdm/cleansed/ivydb-canada/dbo/option-price-2017"},
                {"excludePath": "/src-vdm/cleansed/ivydb-canada/dbo/option-price-2018"},
                {"excludePath": "/src-vdm/cleansed/ivydb-canada/dbo/option-price-2019"},
                {"excludePath": "/src-vdm/cleansed/ivydb-canada/dbo/option-price-2020"},
                {"excludePath": "/src-vdm/cleansed/ivydb-canada/dbo/security-price"},
                {"excludePath": "/src-vdm/cleansed/ivydb-europe/dbo/currency"},
                {"excludePath": "/src-vdm/cleansed/ivydb-europe/dbo/option-price"},
                {"excludePath": "/src-vdm/cleansed/ivydb-europe/dbo/option-price-2002"},
                {"excludePath": "/src-vdm/cleansed/ivydb-europe/dbo/option-price-2003"},
                {"excludePath": "/src-vdm/cleansed/ivydb-europe/dbo/option-price-2004"},
                {"excludePath": "/src-vdm/cleansed/ivydb-europe/dbo/option-price-2005"},
                {"excludePath": "/src-vdm/cleansed/ivydb-europe/dbo/option-price-2006"},
                {"excludePath": "/src-vdm/cleansed/ivydb-europe/dbo/option-price-2007"},
                {"excludePath": "/src-vdm/cleansed/ivydb-europe/dbo/option-price-2008"},
                {"excludePath": "/src-vdm/cleansed/ivydb-europe/dbo/option-price-2009"},
                {"excludePath": "/src-vdm/cleansed/ivydb-europe/dbo/option-price-2010"},
                {"excludePath": "/src-vdm/cleansed/ivydb-europe/dbo/option-price-2011"},
                {"excludePath": "/src-vdm/cleansed/ivydb-europe/dbo/option-price-2012"},
                {"excludePath": "/src-vdm/cleansed/ivydb-europe/dbo/option-price-2013"},
                {"excludePath": "/src-vdm/cleansed/ivydb-europe/dbo/option-price-2014"},
                {"excludePath": "/src-vdm/cleansed/ivydb-europe/dbo/option-price-2015"},
                {"excludePath": "/src-vdm/cleansed/ivydb-europe/dbo/option-price-2016"},
                {"excludePath": "/src-vdm/cleansed/ivydb-europe/dbo/option-price-2017"},
                {"excludePath": "/src-vdm/cleansed/ivydb-europe/dbo/option-price-2018"},
                {"excludePath": "/src-vdm/cleansed/ivydb-europe/dbo/option-price-2019"},
                {"excludePath": "/src-vdm/cleansed/ivydb-europe/dbo/option-price-2020"},
                {"excludePath": "/src-vdm/cleansed/ivydb-europe/dbo/security-price"},
                {"excludePath": "/src-vdm/cleansed/ivydb-us/dbo/option-info"},
                {"excludePath": "/src-vdm/cleansed/ivydb-us/dbo/option-price"},
                {"excludePath": "/src-vdm/cleansed/ivydb-us/dbo/security-price"},
                {"excludePath": "/src-vdm/cleansed/qai/dbo/ds2ctryqtinfo"},
                {"excludePath": "/src-vdm/cleansed/qai/dbo/ds2exchqtinfo"},
                {"excludePath": "/src-vdm/cleansed/qai/dbo/ds2primqtprc"},
                {"excludePath": "/src-vdm/cleansed/qai/dbo/ds2primqtri"},
                {"excludePath": "/src-vdm/cleansed/qai/dbo/fiejvevalprc"},
                {"excludePath": "/src-vdm/cleansed/qai/dbo/fiejvprcdly"},
                {"excludePath": "/src-vdm/cleansed/qai/dbo/fiejvsecinfo"},
                {"excludePath": "/src-vdm/cleansed/qai/dbo/ibesmsrcode"},
                {"excludePath": "/src-vdm/cleansed/qai/dbo/igachg"},
                {"excludePath": "/src-vdm/cleansed/qai/dbo/igactryestdata"},
                {"excludePath": "/src-vdm/cleansed/qai/dbo/igarussestdata"},
                {"excludePath": "/src-vdm/cleansed/qai/dbo/igaspestdata"},
                {"excludePath": "/src-vdm/cleansed/qai/dbo/igatopixestdata"},
                {"excludePath": "/src-vdm/cleansed/qai/dbo/wspitcalprd"},
                {"excludePath": "/src-vdm/cleansed/qai/dbo/wspitcmpissddata"},
                {"excludePath": "/src-vdm/cleansed/qai/dbo/wspitcmpissidata"},
                {"excludePath": "/src-vdm/cleansed/qai/dbo/wspitcmpisssdata"},
                {"excludePath": "/src-vdm/cleansed/qai/dbo/wspitinfo"},
                {"excludePath": "/src-vdm/cleansed/qai/dbo/wspitstmtddata"},
                {"excludePath": "/src-vdm/cleansed/qai/dbo/wspitstmtidata"},
                {"excludePath": "/src-vdm/cleansed/qai/dbo/wspitstmtsdata"},
                {"excludePath": "/src-vdm/cleansed/qai/dbo/wspitsupp"},
                {"excludePath": "/src-vdm/cleansed/vendordatamart/bloomberg/equity-master"},
                {"excludePath": "/src-vdm/cleansed/vendordatamart/bloomberg/equity-price"},
                {"excludePath": "/src-vdm/cleansed/vendordatamart/bloomberg/equity-price-historical-change"},
                {"excludePath": "/src-vdm/cleansed/vendordatamart/bloomberg/equity-price-revision"},
                {"excludePath": "/src-vdm/cleansed/vendordatamart/datastream/security-rz-returns"},
                {"excludePath": "/src-vdm/cleansed/vendordatamart/datastream/series-attributes"},
                {"excludePath": "/src-vdm/cleansed/vendordatamart/dbo/loadfiles"},
                {"excludePath": "/src-vdm/cleansed/vendordatamart/ibes/analyst"},
                {"excludePath": "/src-vdm/cleansed/vendordatamart/ibes/estimates-detail"},
                {"excludePath": "/src-vdm/cleansed/vendordatamart/ibes/estimates-excluded-detail"},
                {"excludePath": "/src-vdm/cleansed/vendordatamart/ibes/report-currency"},
                {"excludePath": "/src-vdm/cleansed/vendordatamart/ibes/summary-statistics"},
                {"excludePath": "/src-vdm/cleansed/vendordatamart/ibes/surprise-history"},
                {"excludePath": "/src-vdm/cleansed/vendordatamart/ibesqfs/actual"},
                {"excludePath": "/src-vdm/cleansed/vendordatamart/ibesqfs/currency-change"},
                {"excludePath": "/src-vdm/cleansed/vendordatamart/ibesqfs/detail-estimate"},
                {"excludePath": "/src-vdm/cleansed/vendordatamart/ibesqfs/summary-estimates"},
                {"excludePath": "/src-vdm/cleansed/vendordatamart/msci/core-infra-monthly"},
                {"excludePath": "/src-vdm/cleansed/xpressfeed/dbo/ciqcompany"},
                {"excludePath": "/src-vdm/cleansed/xpressfeed/dbo/ciqgvkeyiid"},
                # app-gdm curated static exclusions
                {"excludePath": "/app-gdm/curated/assetfour/esg-item-map"},
                {"excludePath": "/app-gdm/curated/barclays/index-map"},
                {"excludePath": "/app-gdm/curated/barclays-live/index-map"},
                {"excludePath": "/app-gdm/curated/barclays-live/lcs-index-map"},
                {"excludePath": "/app-gdm/curated/bloomberg/id-bb-unique-security-id-override"},
                {"excludePath": "/app-gdm/curated/bloomberg/ranged-security-equity"},
                {"excludePath": "/app-gdm/curated/bloomberg/security-type-map"},
                {"excludePath": "/app-gdm/curated/bloomberg/vol-exchange-primary-exchange-map"},
                {"excludePath": "/app-gdm/curated/bloomberg-port/index-map"},
                {"excludePath": "/app-gdm/curated/corporate-action/issuer-action-master"},
                {"excludePath": "/app-gdm/curated/credit/entity-info"},
                {"excludePath": "/app-gdm/curated/credit/entity-item"},
                {"excludePath": "/app-gdm/curated/credit/market-item"},
                {"excludePath": "/app-gdm/curated/credit/rating"},
                {"excludePath": "/app-gdm/curated/credit/rating-item"},
                {"excludePath": "/app-gdm/curated/credit/rating-tier"},
                {"excludePath": "/app-gdm/curated/credit/seniority"},
                {"excludePath": "/app-gdm/curated/credit/tenor"},
                {"excludePath": "/app-gdm/curated/datastream/exchange-map"},
                {"excludePath": "/app-gdm/curated/datastream/macro-series-attributes"},
                {"excludePath": "/app-gdm/curated/datastream/market-data-country-exclusions"},
                {"excludePath": "/app-gdm/curated/datastream/total-return-dscodes-ri"},
                {"excludePath": "/app-gdm/curated/dbo/country"},
                {"excludePath": "/app-gdm/curated/dbo/currency"},
                {"excludePath": "/app-gdm/curated/dbo/euro-conversion-rate"},
                {"excludePath": "/app-gdm/curated/dbo/exchange"},
                {"excludePath": "/app-gdm/curated/dbo/exchange-rate"},
                {"excludePath": "/app-gdm/curated/dbo/gics-group"},
                {"excludePath": "/app-gdm/curated/dbo/gics-industry"},
                {"excludePath": "/app-gdm/curated/dbo/gics-sector"},
                {"excludePath": "/app-gdm/curated/dbo/gics-subindustry"},
                {"excludePath": "/app-gdm/curated/dbo/issuer-info"},
                {"excludePath": "/app-gdm/curated/dbo/issuer-item"},
                {"excludePath": "/app-gdm/curated/dbo/issuer-master"},
                {"excludePath": "/app-gdm/curated/dbo/provider"},
                {"excludePath": "/app-gdm/curated/dbo/security-group-master"},
                {"excludePath": "/app-gdm/curated/dbo/security-hierarchy"},
                {"excludePath": "/app-gdm/curated/dbo/security-hierarchy-master"},
                {"excludePath": "/app-gdm/curated/dbo/security-hierarchy-membership"},
                {"excludePath": "/app-gdm/curated/dbo/security-hierarchy-node"},
                {"excludePath": "/app-gdm/curated/dbo/security-hierarchy-source"},
                {"excludePath": "/app-gdm/curated/dbo/security-info"},
                {"excludePath": "/app-gdm/curated/dbo/security-item"},
                {"excludePath": "/app-gdm/curated/dbo/security-market-item"},
                {"excludePath": "/app-gdm/curated/dbo/security-master"},
                {"excludePath": "/app-gdm/curated/dbo/security-return-bypass"},
                {"excludePath": "/app-gdm/curated/dbo/security-return-factor"},
                {"excludePath": "/app-gdm/curated/dbo/security-split-factor"},
                {"excludePath": "/app-gdm/curated/dbo/security-type"},
                {"excludePath": "/app-gdm/curated/ejv/ejvassetid-security-id-override"},
                {"excludePath": "/app-gdm/curated/ejv/issuer-equity-map"},
                {"excludePath": "/app-gdm/curated/ejv/security-type-map"},
                {"excludePath": "/app-gdm/curated/esg/entity-master"},
                {"excludePath": "/app-gdm/curated/esg/entity-ranged-score"},
                {"excludePath": "/app-gdm/curated/esg/green-revenue-data"},
                {"excludePath": "/app-gdm/curated/esg/index-aggregate-list"},
                {"excludePath": "/app-gdm/curated/esg/item"},
                {"excludePath": "/app-gdm/curated/esg/macro-country-map"},
                {"excludePath": "/app-gdm/curated/esg/mnemonic-list"},
                {"excludePath": "/app-gdm/curated/esg/ranged-controversy-case-score"},
                {"excludePath": "/app-gdm/curated/esg/ranged-paris-alignment-data"},
                {"excludePath": "/app-gdm/curated/esg/ranged-scenario-data"},
                {"excludePath": "/app-gdm/curated/esg/ranged-score"},
                {"excludePath": "/app-gdm/curated/esg/ranged-segment-data"},
                {"excludePath": "/app-gdm/curated/esg/sector"},
                {"excludePath": "/app-gdm/curated/esg/security-type-exclude"},
                {"excludePath": "/app-gdm/curated/factset/ownership-entity-master-map"},
                {"excludePath": "/app-gdm/curated/fixed-income/call-schedule"},
                {"excludePath": "/app-gdm/curated/fixed-income/call-schedule-type"},
                {"excludePath": "/app-gdm/curated/fixed-income/embedded-option-type"},
                {"excludePath": "/app-gdm/curated/fossil-free/esg-item-map"},
                {"excludePath": "/app-gdm/curated/ftse-russell/esg-item-map"},
                {"excludePath": "/app-gdm/curated/ftse-russell/grcs-microsector-map"},
                {"excludePath": "/app-gdm/curated/fundamental/country-lag"},
                {"excludePath": "/app-gdm/curated/fundamental/factset-segment"},
                {"excludePath": "/app-gdm/curated/fundamental/filing"},
                {"excludePath": "/app-gdm/curated/fundamental/filing-detail"},
                {"excludePath": "/app-gdm/curated/fundamental/filing-detail-footnote"},
                {"excludePath": "/app-gdm/curated/fundamental/filing-security-detail"},
                {"excludePath": "/app-gdm/curated/fundamental/filing-segment-detail"},
                {"excludePath": "/app-gdm/curated/fundamental/item"},
                {"excludePath": "/app-gdm/curated/fundamental/vendor-lag"},
                {"excludePath": "/app-gdm/curated/gmo/esg-item-map"},
                {"excludePath": "/app-gdm/curated/haver/geo-code-map"},
                {"excludePath": "/app-gdm/curated/haver/series-code-list"},
                {"excludePath": "/app-gdm/curated/hierarchy/entity-map"},
                {"excludePath": "/app-gdm/curated/hierarchy/entity-type"},
                {"excludePath": "/app-gdm/curated/hierarchy/hierarchy"},
                {"excludePath": "/app-gdm/curated/hierarchy/hierarchy-type"},
                {"excludePath": "/app-gdm/curated/ibes/adjustment-factor-override"},
                {"excludePath": "/app-gdm/curated/ibes/estimate-aggregation-map"},
                {"excludePath": "/app-gdm/curated/ibes/estimate-analyst-map"},
                {"excludePath": "/app-gdm/curated/ibes/estimate-broker-map"},
                {"excludePath": "/app-gdm/curated/ibes/estimate-country-map"},
                {"excludePath": "/app-gdm/curated/ibes/estimate-dilution-map"},
                {"excludePath": "/app-gdm/curated/ibes/estimate-gics-map"},
                {"excludePath": "/app-gdm/curated/ibes/estimate-index-map"},
                {"excludePath": "/app-gdm/curated/ibes/forecast-period-indicator-map"},
                {"excludePath": "/app-gdm/curated/ibes/fundamental-item-map"},
                {"excludePath": "/app-gdm/curated/index-data/constituent"},
                {"excludePath": "/app-gdm/curated/index-data/fi-returns-statistics-index-map"},
                {"excludePath": "/app-gdm/curated/index-data/index-master"},
                {"excludePath": "/app-gdm/curated/index-data/index-security-attribute"},
                {"excludePath": "/app-gdm/curated/index-data/market-item"},
                {"excludePath": "/app-gdm/curated/internal/credit-entity"},
                {"excludePath": "/app-gdm/curated/internal/credit-entity-market-data"},
                {"excludePath": "/app-gdm/curated/internal/credit-rating"},
                {"excludePath": "/app-gdm/curated/internal/days"},
                {"excludePath": "/app-gdm/curated/internal/estimate-detail"},
                {"excludePath": "/app-gdm/curated/internal/estimate-entity"},
                {"excludePath": "/app-gdm/curated/internal/estimate-summary"},
                {"excludePath": "/app-gdm/curated/internal/exchange-calendar"},
                {"excludePath": "/app-gdm/curated/internal/index-market-data"},
                {"excludePath": "/app-gdm/curated/internal/issuer-market-cap-data"},
                {"excludePath": "/app-gdm/curated/internal/macro-entity"},
                {"excludePath": "/app-gdm/curated/internal/macro-factors"},
                {"excludePath": "/app-gdm/curated/internal/macro-info"},
                {"excludePath": "/app-gdm/curated/internal/security-dividend"},
                {"excludePath": "/app-gdm/curated/internal/security-group-membership"},
                {"excludePath": "/app-gdm/curated/internal/security-index-map"},
                {"excludePath": "/app-gdm/curated/internal/security-market-data"},
                {"excludePath": "/app-gdm/curated/internal/security-split"},
                {"excludePath": "/app-gdm/curated/macro/primary-source"},
                {"excludePath": "/app-gdm/curated/macro/series"},
                {"excludePath": "/app-gdm/curated/macro/series-group"},
                {"excludePath": "/app-gdm/curated/marketaxess/transactions"},
                {"excludePath": "/app-gdm/curated/markit-parsing/security-type-map"},
                {"excludePath": "/app-gdm/curated/model/esg-component-data-cache"},
                {"excludePath": "/app-gdm/curated/model/esg-component-data-cache-country-code-override"},
                {"excludePath": "/app-gdm/curated/model/esg-indicator-component"},
                {"excludePath": "/app-gdm/curated/model/gmo-model-meta"},
                {"excludePath": "/app-gdm/curated/msci/ranged-security"},
                {"excludePath": "/app-gdm/curated/msci-esg/esg-item-map"},
                {"excludePath": "/app-gdm/curated/override/currency-revaluation"},
                {"excludePath": "/app-gdm/curated/override/dbo-issuer-info"},
                {"excludePath": "/app-gdm/curated/override/dbo-security-info"},
                {"excludePath": "/app-gdm/curated/override/estimate-summary"},
                {"excludePath": "/app-gdm/curated/override/exchange-calendar"},
                {"excludePath": "/app-gdm/curated/override/exchange-rate"},
                {"excludePath": "/app-gdm/curated/override/fundamental-factset-segment"},
                {"excludePath": "/app-gdm/curated/override/fundamental-filing"},
                {"excludePath": "/app-gdm/curated/override/fundamental-filing-detail"},
                {"excludePath": "/app-gdm/curated/override/index-data-constituent"},
                {"excludePath": "/app-gdm/curated/override/index-market"},
                {"excludePath": "/app-gdm/curated/override/internal-credit-rating"},
                {"excludePath": "/app-gdm/curated/override/override-master"},
                {"excludePath": "/app-gdm/curated/override/security-dividend"},
                {"excludePath": "/app-gdm/curated/override/security-group-membership"},
                {"excludePath": "/app-gdm/curated/override/security-hierarchy-membership"},
                {"excludePath": "/app-gdm/curated/override/security-index-map"},
                {"excludePath": "/app-gdm/curated/override/security-market"},
                {"excludePath": "/app-gdm/curated/override/security-split"},
                {"excludePath": "/app-gdm/curated/ownership/entity-master"},
                {"excludePath": "/app-gdm/curated/ownership/position"},
                {"excludePath": "/app-gdm/curated/portfolio/position"},
                {"excludePath": "/app-gdm/curated/priority/credit-market"},
                {"excludePath": "/app-gdm/curated/reference/barclays-to-bloomberg-class-map"},
                {"excludePath": "/app-gdm/curated/reference/country-currency-map"},
                {"excludePath": "/app-gdm/curated/sasb/activity-metric"},
                {"excludePath": "/app-gdm/curated/sasb/industry"},
                {"excludePath": "/app-gdm/curated/sasb/metric"},
                {"excludePath": "/app-gdm/curated/sasb/msci-esg-issue-map"},
                {"excludePath": "/app-gdm/curated/sasb/msci-esg-metric-map"},
                {"excludePath": "/app-gdm/curated/sasb/ranged-security-data"},
                {"excludePath": "/app-gdm/curated/sasb/sasb-key-security-id-override"},
                {"excludePath": "/app-gdm/curated/sasb/sector"},
                {"excludePath": "/app-gdm/curated/sasb/sub-activity-metric"},
                {"excludePath": "/app-gdm/curated/sasb/sub-metric"},
                {"excludePath": "/app-gdm/curated/sasb/topic"},
                {"excludePath": "/app-gdm/curated/sasb/un-sdg-map"},
                {"excludePath": "/app-gdm/curated/temporal/esg-ranged-score-history"},
                {"excludePath": "/app-gdm/curated/trucost/esg-item-map"},
                {"excludePath": "/app-gdm/curated/truvalue/esg-item-map"},
                # GDM history tables (excluding current quarter 2025_q4)
                {"excludePath": "/app-gdm/curated/gdm/history/credit-entity-info/2024_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-entity-info/2024_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-entity-info/2024_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-entity-info/2024_q4/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-entity-info/2025_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-entity-info/2025_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-entity-info/2025_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-entity-item/2024_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-entity-item/2024_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-entity-item/2024_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-entity-item/2024_q4/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-entity-item/2025_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-entity-item/2025_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-entity-item/2025_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-market-item/2024_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-market-item/2024_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-market-item/2024_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-market-item/2024_q4/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-market-item/2025_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-market-item/2025_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-market-item/2025_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-rating/2024_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-rating/2024_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-rating/2024_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-rating/2024_q4/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-rating/2025_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-rating/2025_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-rating/2025_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-rating-item/2024_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-rating-item/2024_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-rating-item/2024_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-rating-item/2024_q4/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-rating-item/2025_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-rating-item/2025_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-rating-item/2025_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-rating-tier/2024_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-rating-tier/2024_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-rating-tier/2024_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-rating-tier/2024_q4/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-rating-tier/2025_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-rating-tier/2025_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-rating-tier/2025_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-seniority/2024_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-seniority/2024_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-seniority/2024_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-seniority/2024_q4/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-seniority/2025_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-seniority/2025_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-seniority/2025_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-tenor/2024_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-tenor/2024_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-tenor/2024_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-tenor/2024_q4/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-tenor/2025_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-tenor/2025_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/credit-tenor/2025_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/datastream-macro-series-attribute-item-override/2024_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/datastream-macro-series-attribute-item-override/2024_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/datastream-macro-series-attribute-item-override/2024_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/datastream-macro-series-attribute-item-override/2024_q4/"},
                {"excludePath": "/app-gdm/curated/gdm/history/datastream-macro-series-attribute-item-override/2025_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/datastream-macro-series-attribute-item-override/2025_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/datastream-macro-series-attribute-item-override/2025_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/datastream-macro-series-attributes/2024_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/datastream-macro-series-attributes/2024_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/datastream-macro-series-attributes/2024_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/datastream-macro-series-attributes/2024_q4/"},
                {"excludePath": "/app-gdm/curated/gdm/history/datastream-macro-series-attributes/2025_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/datastream-macro-series-attributes/2025_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/datastream-macro-series-attributes/2025_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/dbo-issuer-master/2024_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/dbo-issuer-master/2024_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/dbo-issuer-master/2024_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/dbo-issuer-master/2024_q4/"},
                {"excludePath": "/app-gdm/curated/gdm/history/dbo-issuer-master/2025_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/dbo-issuer-master/2025_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/dbo-issuer-master/2025_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/dbo-security-master/2024_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/dbo-security-master/2024_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/dbo-security-master/2024_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/dbo-security-master/2024_q4/"},
                {"excludePath": "/app-gdm/curated/gdm/history/dbo-security-master/2025_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/dbo-security-master/2025_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/dbo-security-master/2025_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/dbo-security-split-factor/2024_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/dbo-security-split-factor/2024_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/dbo-security-split-factor/2024_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/dbo-security-split-factor/2024_q4/"},
                {"excludePath": "/app-gdm/curated/gdm/history/dbo-security-split-factor/2025_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/dbo-security-split-factor/2025_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/dbo-security-split-factor/2025_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/esg-green-revenue-data/2024_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/esg-green-revenue-data/2024_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/esg-green-revenue-data/2024_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/esg-green-revenue-data/2024_q4/"},
                {"excludePath": "/app-gdm/curated/gdm/history/esg-green-revenue-data/2025_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/esg-green-revenue-data/2025_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/esg-green-revenue-data/2025_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/index-data-constituent/2024_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/index-data-constituent/2024_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/index-data-constituent/2024_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/index-data-constituent/2024_q4/"},
                {"excludePath": "/app-gdm/curated/gdm/history/index-data-constituent/2025_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/index-data-constituent/2025_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/index-data-constituent/2025_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-credit-entity/2024_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-credit-entity/2024_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-credit-entity/2024_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-credit-entity/2024_q4/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-credit-entity/2025_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-credit-entity/2025_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-credit-entity/2025_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-credit-entity-market-data/2024_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-credit-entity-market-data/2024_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-credit-entity-market-data/2024_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-credit-entity-market-data/2024_q4/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-credit-entity-market-data/2025_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-credit-entity-market-data/2025_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-credit-entity-market-data/2025_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-credit-rating/2024_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-credit-rating/2024_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-credit-rating/2024_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-credit-rating/2024_q4/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-credit-rating/2025_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-credit-rating/2025_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-credit-rating/2025_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-issuer-market-cap-data/2024_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-issuer-market-cap-data/2024_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-issuer-market-cap-data/2024_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-issuer-market-cap-data/2024_q4/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-issuer-market-cap-data/2025_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-issuer-market-cap-data/2025_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-issuer-market-cap-data/2025_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-macro-entity/2024_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-macro-entity/2024_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-macro-entity/2024_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-macro-entity/2024_q4/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-macro-entity/2025_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-macro-entity/2025_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-macro-entity/2025_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-macro-factors/2024_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-macro-factors/2024_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-macro-factors/2024_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-macro-factors/2024_q4/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-macro-factors/2025_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-macro-factors/2025_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-macro-factors/2025_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-macro-info/2024_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-macro-info/2024_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-macro-info/2024_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-macro-info/2024_q4/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-macro-info/2025_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-macro-info/2025_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-macro-info/2025_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-security-dividend/2024_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-security-dividend/2024_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-security-dividend/2024_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-security-dividend/2024_q4/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-security-dividend/2025_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-security-dividend/2025_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-security-dividend/2025_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-security-split/2024_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-security-split/2024_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-security-split/2024_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-security-split/2024_q4/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-security-split/2025_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-security-split/2025_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/internal-security-split/2025_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/macro-primary-source/2024_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/macro-primary-source/2024_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/macro-primary-source/2024_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/macro-primary-source/2024_q4/"},
                {"excludePath": "/app-gdm/curated/gdm/history/macro-primary-source/2025_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/macro-primary-source/2025_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/macro-primary-source/2025_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/macro-series/2024_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/macro-series/2024_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/macro-series/2024_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/macro-series/2024_q4/"},
                {"excludePath": "/app-gdm/curated/gdm/history/macro-series/2025_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/macro-series/2025_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/macro-series/2025_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/priority-credit-market/2024_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/priority-credit-market/2024_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/priority-credit-market/2024_q3/"},
                {"excludePath": "/app-gdm/curated/gdm/history/priority-credit-market/2024_q4/"},
                {"excludePath": "/app-gdm/curated/gdm/history/priority-credit-market/2025_q1/"},
                {"excludePath": "/app-gdm/curated/gdm/history/priority-credit-market/2025_q2/"},
                {"excludePath": "/app-gdm/curated/gdm/history/priority-credit-market/2025_q3/"},
                # Astral history tables (excluding current quarter 2025_q4)
                {"excludePath": "/app-gdm/curated/astral/history/gdm-currency-cross-rate/2024_q1/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-currency-cross-rate/2024_q2/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-currency-cross-rate/2024_q3/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-currency-cross-rate/2024_q4/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-currency-cross-rate/2025_q1/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-currency-cross-rate/2025_q2/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-currency-cross-rate/2025_q3/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-estimate-summary/2024_q1/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-estimate-summary/2024_q2/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-estimate-summary/2024_q3/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-estimate-summary/2024_q4/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-estimate-summary/2025_q1/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-estimate-summary/2025_q2/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-estimate-summary/2025_q3/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-filing/2024_q1/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-filing/2024_q2/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-filing/2024_q3/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-filing/2024_q4/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-filing/2025_q1/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-filing/2025_q2/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-filing/2025_q3/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-filing-detail/2024_q1/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-filing-detail/2024_q2/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-filing-detail/2024_q3/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-filing-detail/2024_q4/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-filing-detail/2025_q1/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-filing-detail/2025_q2/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-filing-detail/2025_q3/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-index-market-data/2024_q1/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-index-market-data/2024_q2/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-index-market-data/2024_q3/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-index-market-data/2024_q4/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-index-market-data/2025_q1/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-index-market-data/2025_q2/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-index-market-data/2025_q3/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-issuer-hierarchy/2024_q1/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-issuer-hierarchy/2024_q2/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-issuer-hierarchy/2024_q3/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-issuer-hierarchy/2024_q4/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-issuer-hierarchy/2025_q1/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-issuer-hierarchy/2025_q2/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-issuer-hierarchy/2025_q3/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-issuer-hierarchy-ultimate-parent/2024_q1/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-issuer-hierarchy-ultimate-parent/2024_q2/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-issuer-hierarchy-ultimate-parent/2024_q3/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-issuer-hierarchy-ultimate-parent/2024_q4/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-issuer-hierarchy-ultimate-parent/2025_q1/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-issuer-hierarchy-ultimate-parent/2025_q2/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-issuer-hierarchy-ultimate-parent/2025_q3/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-issuer-info/2024_q1/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-issuer-info/2024_q2/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-issuer-info/2024_q3/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-issuer-info/2024_q4/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-issuer-info/2025_q1/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-issuer-info/2025_q2/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-issuer-info/2025_q3/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-security-info/2024_q1/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-security-info/2024_q2/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-security-info/2024_q3/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-security-info/2024_q4/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-security-info/2025_q1/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-security-info/2025_q2/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-security-info/2025_q3/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-security-market-data/2024_q1/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-security-market-data/2024_q2/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-security-market-data/2024_q3/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-security-market-data/2024_q4/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-security-market-data/2025_q1/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-security-market-data/2025_q2/"},
                {"excludePath": "/app-gdm/curated/astral/history/gdm-security-market-data/2025_q3/"},
                {"excludePath": "/app-gdm/curated/astral/history/gmo-security-master-feed/2024_q1/"},
                {"excludePath": "/app-gdm/curated/astral/history/gmo-security-master-feed/2024_q2/"},
                {"excludePath": "/app-gdm/curated/astral/history/gmo-security-master-feed/2024_q3/"},
                {"excludePath": "/app-gdm/curated/astral/history/gmo-security-master-feed/2024_q4/"},
                {"excludePath": "/app-gdm/curated/astral/history/gmo-security-master-feed/2025_q1/"},
                {"excludePath": "/app-gdm/curated/astral/history/gmo-security-master-feed/2025_q2/"},
                {"excludePath": "/app-gdm/curated/astral/history/gmo-security-master-feed/2025_q3/"},
            ],
            "fsContentOperationType": "OVERWRITE",
            "fsExcludeFilterOperationType": "OVERWRITE",
            "fsIncludeFilterOperationType": "CLEAR"
        }
    }
    return json.dumps(payload)

def send_post_request(url, headers, payload):
    """
    Sends a POST request to the specified URL with the given headers and payload.

    Args:
        url (str): The API endpoint URL.
        headers (dict): The HTTP headers to include in the request.
        payload (str): The JSON-formatted payload as a string.

    Returns:
        str: The response text if the request is successful; otherwise, None.
    """
    try:
        response = requests.post(url, headers=headers, data=payload, verify=False)  # Set verify=True in production
        response.raise_for_status()  # Raise an HTTPError for bad responses (4xx or 5xx)
        return response.text
    except requests.exceptions.HTTPError as http_err:
        print(f"[HTTP ERROR] {http_err}")  # e.g., 404 Not Found
    except requests.exceptions.RequestException as req_err:
        print(f"[REQUEST ERROR] {req_err}")  # Network-related errors
    except Exception as err:
        print(f"[ERROR] An unexpected error occurred: {err}")  # Other errors
    return None

def pretty_print_response(response_text):
    """
    Formats and prints the XML response to be more human-readable.

    Args:
        response_text (str): The raw XML response as a string.
    """
    try:
        # Parse the XML string into a DOM object
        dom = xml.dom.minidom.parseString(response_text)
        # Generate a pretty-printed XML string with indentation
        pretty_xml = dom.toprettyxml(indent="    ")
        print(pretty_xml)
    except Exception as e:
        print(f"[ERROR] Failed to parse XML response: {e}")
        print("Original Response:")
        print(response_text)

def main():
    """
    Main function to execute the workflow:
    1. Build the payload.
    2. Send the POST request.
    3. Pretty-print the response.
    """
    url = "https://commvault-server/commandcenter/api/Subclient/1776"

    # Retrieve the API authentication token from environment variables
    auth_token = os.getenv("API_AUTH_TOKEN")
    if not auth_token:
        print("Error: API_AUTH_TOKEN environment variable is not set.")
        return

    headers = {
        "Authorization": auth_token,
        "Content-Type": "application/json"
    }

    # Build the payload
    payload = build_payload()

    # Send the POST request and get the response
    response = send_post_request(url, headers, payload)

    if response:
        # Pretty-print the response
        pretty_print_response(response)
    else:
        print("Failed to retrieve a valid response from the API.")

if __name__ == "__main__":
    main()
